name: Merge Submodule PRs

on:
  pull_request:
    types: [closed]

jobs:
  merge-submodules:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Merge PR in ee-server (if exists)
        run: |
          PR=$(gh pr list -R ToolJet/ee-server --head "$BRANCH_NAME" --state open --json number -q '.[0].number')
          if [ -n "$PR" ]; then
            echo "Found ee-server PR: #$PR"
            gh pr merge -R ToolJet/ee-server "$PR" --merge --admin
          else
            echo "No open ee-server PR for branch $BRANCH_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR in ee-frontend (if exists)
        run: |
          PR=$(gh pr list -R ToolJet/ee-frontend --head "$BRANCH_NAME" --state open --json number -q '.[0].number')
          if [ -n "$PR" ]; then
            echo "Found ee-frontend PR: #$PR"
            gh pr merge -R ToolJet/ee-frontend "$PR" --merge --admin
          else
            echo "No open ee-frontend PR for branch $BRANCH_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
