name: Merge Submodule PRs

on:
  pull_request:
    types: [closed]

jobs:
  merge-submodules:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        run: echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Merge PR in ee-server (if exists)
        run: |
          PR=$(gh pr list -R akshaysasidrn/todo-server-submodule --head "$BRANCH_NAME" --state open --json number -q '.[0].number')
          if [ -n "$PR" ]; then
            echo "Found todo-server-submodule PR: #$PR"
            gh pr merge -R akshaysasidrn/todo-server-submodule "$PR" --merge --admin
          else
            echo "No open todo-server-submodule PR for branch $BRANCH_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR in ee-frontend (if exists)
        run: |
          PR=$(gh pr list -R akshaysasidrn/todo-frontend-submodule --head "$BRANCH_NAME" --state open --json number -q '.[0].number')
          if [ -n "$PR" ]; then
            echo "Found todo-frontend-submodule PR: #$PR"
            gh pr merge -R akshaysasidrn/todo-frontend-submodule "$PR" --merge --admin
          else
            echo "No open todo-frontend-submodule PR for branch $BRANCH_NAME"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
